### ISSUE TITLE
How to generate Poisson distribution?

### ISSUE THREAD

**Issue by SalarJamal** [drmibell/node-red-contrib-random-event-generator#5]
I am working on a project and I want to generate events in Poisson distribution form, the "event node" doesn't support Poisson, could you help me Please.
![Untitled](https://user-images.githubusercontent.com/90519454/170689622-26819ce3-5412-4994-b3b2-44203e70f4ed.jpg)

**Comment by drmibell** [comment]
The node should do what you want if the distribution is set to "exponential." The terms "exponential" and "Poisson" refer to different aspects of the same thing. For a Poisson process, the intervals between events are given by an exponential distribution, while the number of events observed in a specified time interval is given by a Poisson distribution. The documentation and edit dialog use the word "exponential," because this is technically correct. It might be helpful to refer to a Poisson process in the documentation.

**Comment by SalarJamal** [comment]
Thank you Dear.
